version: '3.9'
services:
  api_socket:
    build: { context: ./backend/socket, target: prod }
    container_name: ing_master_webp_api_socket
    env_file: ./backend/socket/.env
    command: ["gunicorn","-k","uvicorn.workers.UvicornWorker","-w","1","-t","1","-b","0.0.0.0:80","main:app"]
    restart: unless-stopped

  front_web:
    build: { context: ./frontend/web, target: prod }
    container_name: ing_master_webp_front_web
    env_file: ./frontend/web/.env_prod
    restart: unless-stopped

  proxy:
    build: { context: ./nginx }
    container_name: ing_master_webp_proxy
    ports: [ '80:80', '443:443' ]
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./nginx/proxy_params.conf:/etc/nginx/proxy_params.conf:ro
      - ./nginx/certbot/www:/var/www/certbot:ro
      - ./nginx/letsencrypt:/etc/letsencrypt:ro
    depends_on: [api_socket, front_web]
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: ing_master_webp_certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/letsencrypt:/etc/letsencrypt
    depends_on: [proxy]
    entrypoint: sh
    command: -c "if [ -n 'api.socket.ingenieriamaster.com.co web.ingenieriamaster.com.co www.web.ingenieriamaster.com.co' ]; then for d in api.socket.ingenieriamaster.com.co web.ingenieriamaster.com.co www.web.ingenieriamaster.com.co; do certbot certonly -n --keep-until-expiring --webroot -w /var/www/certbot -d $$d --email \"andrew19f@gmail.com\" --agree-tos --no-eff-email ; done; fi; trap exit TERM; while :; do certbot renew -n --webroot -w /var/www/certbot --quiet || true; sleep 12h; done"
    restart: unless-stopped
